version: "3"
services:
  api:
    build: ./api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9229:9229"
  web:
    build: ./web
    depends_on:
      - api
    ports:
      - 3000:3000
  postgres:
    image: postgres:9.6.8-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./api/scripts/db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres
